#!/opt/anaconda/bin/python
import sys
import os
import os.path
import atexit

# import the ciop functions (e.g. copy, log)
import cioppy

ciop = cioppy.Cioppy()

# define the exit codes
SUCCESS = 0
ERR_NOINPUT = 1

# add a trap to exit gracefully
def clean_exit(exit_code):
    log_level = 'INFO'
    if exit_code != SUCCESS:
        log_level = 'ERROR'

    msg = { SUCCESS: 'Processing successfully concluded',
           ERR_NOINPUT: 'No input provided'}

    ciop.log(log_level, msg[exit_code])

def main():
    
    print("This test aims to verify the correct behaviour of the cioppy.publish whit option mode = anonymous (first part of the test)")

    # Loops over all the inputs
    for inputfile in sys.stdin:

        ciop.log("INFO", "Retrieving " + inputfile)
        retrieved = ciop.copy(inputfile, ciop.tmp_dir, False)
        assert(os.path.isfile(retrieved) == True)
        ciop.log("INFO", "Retrieved " + retrieved)

        file_to_publish = os.path.join(ciop.tmp_dir, os.path.basename(inputfile))

        ciop.log("INFO", "Publishing result (" + file_to_publish + ")")

        anonymous_publishing = ciop.publish(file_to_publish , mode='anonymous') 

        text_on_screen = "<" + anonymous_publishing + ">"

        print(text_on_screen)
        silent_publishing = ciop.publish(text_on_screen , mode='silent')     

# execute test
try:
    main()
except SystemExit as e:
    if e.args[0]:
        clean_exit(e.args[0])
    raise
else:
    atexit.register(clean_exit, 0)